## spring配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mmall?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: TANGqi0924
    driver-class-name: com.mysql.cj.jdbc.Driver
## mybatis配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/southwind/mapper/xml/*.xml
## 端口配置
server:
  port: 8089
